//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroX_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class dose_measurements
    {
        public int meas_nr { get; set; }
        public string tube_nr { get; set; }
        public Nullable<int> kv { get; set; }
        public Nullable<int> ic_init { get; set; }
        public Nullable<int> ic_limit { get; set; }
        public Nullable<float> kvp_a { get; set; }
        public Nullable<float> mas { get; set; }
        public Nullable<float> ms { get; set; }
        public Nullable<float> dose { get; set; }
        public Nullable<bool> fromeol { get; set; }
    
        public virtual tube_data tube_data { get; set; }
    }
}
