//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroX_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class eol_shot
    {
        public int shot_nr { get; set; }
        public string tube_nr { get; set; }
        public Nullable<int> kv { get; set; }
        public Nullable<float> mas { get; set; }
        public Nullable<float> t { get; set; }
        public Nullable<float> ia { get; set; }
        public Nullable<float> ic { get; set; }
        public Nullable<int> vf { get; set; }
        public Nullable<float> @if { get; set; }
    
        public virtual tube_data tube_data { get; set; }
    }
}
