//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroX_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class fss_data
    {
        public int fss_nr { get; set; }
        public string tube_nr { get; set; }
        public Nullable<int> kv { get; set; }
        public Nullable<int> vf { get; set; }
        public Nullable<float> fsl { get; set; }
        public Nullable<float> fsw { get; set; }
    
        public virtual tube_data tube_data { get; set; }
    }
}
