//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroX_database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tube_data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tube_data()
        {
            this.dose_measurements = new HashSet<dose_measurements>();
            this.eol_shot = new HashSet<eol_shot>();
            this.exposure_data = new HashSet<exposure_data>();
            this.fss_data = new HashSet<fss_data>();
            this.tube_system = new HashSet<tube_system>();
            this.testers = new HashSet<tester>();
        }
    
        public string tube_nr { get; set; }
        public string cathode_nr { get; set; }
        public Nullable<float> gc_height_avg { get; set; }
        public Nullable<float> gc_height_min { get; set; }
        public Nullable<float> gc_height_max { get; set; }
        public Nullable<float> gc_height_stdev { get; set; }
        public Nullable<float> r_25 { get; set; }
        public Nullable<float> r_60 { get; set; }
        public Nullable<int> eol_r_grid { get; set; }
        public Nullable<int> eol_vz { get; set; }
        public Nullable<int> eol_focus_corr { get; set; }
        public Nullable<float> eol_ia { get; set; }
        public Nullable<float> eol_ic { get; set; }
        public Nullable<float> eol_t { get; set; }
        public Nullable<int> eol_v_grid_peak { get; set; }
        public Nullable<float> eol_ia_55kv_09mm { get; set; }
        public Nullable<float> eol_ifs_09mm { get; set; }
        public Nullable<float> eol_ifs_19mm { get; set; }
        public Nullable<float> eq_alum_half { get; set; }
        public Nullable<int> eq_alum_ic_init { get; set; }
        public Nullable<int> eq_alum_ic_limit { get; set; }
        public string station_id { get; set; }
        public string slit_diaphragm { get; set; }
        public string carestream_hpx { get; set; }
        public string focal_spot_stand { get; set; }
        public string film1 { get; set; }
        public string film2 { get; set; }
        public string raysafe_base_unit { get; set; }
        public string raysafe_sensor { get; set; }
        public Nullable<float> disc_thickness { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dose_measurements> dose_measurements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eol_shot> eol_shot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exposure_data> exposure_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fss_data> fss_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tube_system> tube_system { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tester> testers { get; set; }
    }
}
